madminer-tool/madminer

README.md
The README link to the mining gold paper was pointing to the constraining EFT with ML guide, fixed now.
=> Fixed link to mining gold paper

examples/toy_example/toy_example.ipynb, madminer/utils/ml/ratio_trainer.py, madminer/utils/ml/score_trainer.py
When running on GPUs, the model evaluation step throws the following error for me: `TypeError: can't convert CUDA tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.`. This is fixed with this MR. I am not sure whether this is related to the systems and environments I have used to test this and it works already without this fix on different setups.
Besides, the `corner` library is no longer needed for the toy example, so the import was removed.
=> Copying back tensors to CPU for model evaluation when running on GPUs to prevent crash, minor tutorial update

madminer/sampling/sampleaugmenter.py
This PR mainly updates the `SampleAugmenter` methods doc strings, as their arguments were changed in [this commit](https://github.com/diana-hep/madminer/commit/fa3e2e8f4ca40418b8b589d7d88a3a64c9e65878), but the doc strings were not.
In addition, I have added some unused method arguments into their `self.sample_train_local` and `self._sample` subcalls. I have assumed that _"downfall argument propagation"_ was desired when implementing these methods.
Finally, I think there is no need for a version bump up. Feel free to it if you think so.
=> Update outdated doc strings

madminer/core/madminer.py, madminer/utils/interfaces/mg.py
This PR brings aesthetic changes to the MadMiner `core` and `utils` packages. Basically:
- Deletion of duplicated doc-string arguments.
- Deletion of redundant `/` character when defining MadGraph card paths (every time those variables are used, they are preceded by a `+ '/' + ` snippet).
- Deletion of unnecessary argument check when calling [setup_mg_with_scripts](https://github.com/diana-hep/madminer/blob/master/madminer/core/madminer.py#L1007) within the [run_multiple](https://github.com/diana-hep/madminer/blob/master/madminer/core/madminer.py#L784) function (Unless something more logical was planned to occur there, and due to typos ended up as a silly logic).
- Fix doc-string arguments indentation.
Due to the nature of this PR, I have not updated the version.
=> Improve 'core' and 'utils' doc strings

madminer/delphes/delphes_reader.py
This PR aims to improve the input verification of:
- [DelphesReader.add_sample](https://github.com/diana-hep/madminer/blob/master/madminer/delphes/delphes_reader.py#L106), receiving file paths
- [DelphesReader.add_observable](https://github.com/diana-hep/madminer/blob/master/madminer/delphes/delphes_reader.py#L300), receiving Python expressions in string format.
- [DelphesReader.add_cut](https://github.com/diana-hep/madminer/blob/master/madminer/delphes/delphes_reader.py#L469), receiving Python expressions in string format
By checking for valid inputs before performing any further actions.
**Considerations:**
1. The [DelphesReader.add_sample](https://github.com/diana-hep/madminer/blob/master/madminer/delphes/delphes_reader.py#L106) function has also suffered a re-organization of these …
=> Improve DelphesReader input checks

Dockerfile
**~Disclaimer: `root-ubuntu20` image is not yet published. Do NOT merge.~**
Following the refactor performed in the [Scailfin/madminer-workflow](https://github.com/scailfin/workflow-madminer) repository, a base image with newer Python3 version was needed (at least Python 3.6).
I realized the base image Madminer used for its Docker image, `rootproject/root-ubuntu16`, was lagging behind the current state of Ubuntu (currently at Ubuntu 20.04). Therefore, I proposed an [upgrade to Ubuntu20 ](https://github.com/root-project/root-docker/pull/11), which has been recently approved.
I am assuming it will soon be published under the `rootproject` Dockerhub account.
---
In addition:
- I have listed the required `apt-get` packages in a vertical fashion.
- I have added the `--no-cache-dir` option to …
=> Update dockerfile to Ubuntu 20.04

Dockerfile
This PR fixes some non-considered bugs introduced in the previous PR (https://github.com/diana-hep/madminer/pull/427):
1. From Ubuntu 20.04, Python2 `pip` package can no longer be installed using the `python-pip` rule. I followed [this guide](https://linuxize.com/post/how-to-install-pip-on-ubuntu-20.04/#installing-pip-for-python-2) in order to get Python2 `pip` from the Python Package Authority ([PyPA](https://github.com/pypa)).
2. When installing MadMiner, `python-dev` instead of `python` need to be installed. The _"-dev"_ version includes the necessary headers for building the `subprocess32` binary.
---
Sorry for letting these bugs slip in...
=> Fix dockerfile Python2 installation

examples/tutorial_particle_physics/1_setup.ipynb, examples/tutorial_particle_physics/2a_parton_level_analysis.ipynb, examples/tutorial_particle_physics/2b_delphes_level_analysis.ipynb, examples/tutorial_particle_physics/3a_likelihood_ratio.ipynb, examples/tutorial_particle_physics/3b_score.ipynb, examples/tutorial_particle_physics/3c_likelihood.ipynb, examples/tutorial_particle_physics/4a_limits.ipynb, examples/tutorial_particle_physics/4b_fisher_information.ipynb, examples/tutorial_particle_physics/4c_information_geometry.ipynb, examples/tutorial_particle_physics/A1_systematic_uncertainties.ipynb
This PR updates the [particle_physics](https://github.com/diana-hep/madminer/tree/master/examples/tutorial_particle_physics) tutorial Jupyter notebooks  within the `examples` folder, by:
- Updating the logged version of the package (now `0.7.4`).
- Updating the path to where MadGraph 5 is installed (check [its env. Dockerfile](https://github.com/scailfin/madminer-jupyter-env/blob/master/Dockerfile#L37) and [this similar PR](https://github.com/cranmer/madminer-tutorial/pull/2)).
- Updating the MadGraph folder version to `2.6.7`
---
Most of the changes are aesthetic, but for the MadGraph path one. If that is not changed the tutorial will not work.
=> Update particle physics tutorial

madminer/core/madminer.py, madminer/utils/interfaces/lhe.py, madminer/utils/interfaces/mg.py, madminer/utils/interfaces/mg_cards.py
Hi,
I've added an `order` setting to accommodate differences between LO and NLO computations.
The changes are as follows:
* Removes the `use_syst` option from the run card at NLO
* Pythia card is named `shower_card.dat` at NLO
* At NLO, in lhe files there is an additional line starting with `#aMCatNLO`
* I think this line does not contain particles and maybe a better way would be to skip this line entirely, but for now it checks the "status"
Hopefully, this `order` setting is useful in the future as well!
=> addition of order; Reading NLO lhe files

madminer/__info__.py, madminer/utils/interfaces/delphes_root.py, setup.py
This PR addresses issue https://github.com/diana-hep/madminer/issues/453 by setting **lower / upper bounds** to the set of [setup.py](https://github.com/diana-hep/madminer/blob/master/setup.py#L36-L46) unbounded dependencies.
The most immediate problem to address is the recent incompatibility with the newest version of [uproot](https://uproot.readthedocs.io/en/latest/) (`uproot4`), which **breaks** some of the public methods / attributes being used within the [madminer/utils/interfaces/delphes_root.py](https://github.com/diana-hep/madminer/blob/master/madminer/utils/interfaces/delphes_root.py) module (check the list of [uproot4 removed features](https://uproot.readthedocs.io/en/latest/uproot3-to-4.html#removed-features)).
- Bump up package version to `0.7.7`.
Additional dependency …
=> Bound dependency versions

.readthedocs.yml
This PR is supposed to fix the [read-the-docs](https://readthedocs.org/) building process, which has been broken since July 1st 2020 ([check here](https://readthedocs.org/projects/madminer/builds/)).
The problem seems to be the missing installation of `numpydoc`, which has been perfectly declared in [the setup.py `docs` section](https://github.com/diana-hep/madminer/blob/master/setup.py#L49) for a long time now. Therefore, my intuition tells me that the _read-the-docs_ folks changed the build process at some point during the last year, requiring a `.readthedocs.yml` file to be declared now.
=> Define read-the-docs config file

docs/conf.py, docs/index.rst, docs/modules.rst, setup.py
This PR replaces the legacy [readthedocs/recommonmark](https://github.com/readthedocs/recommonmark) package by its direct substitution: [executablebooks/MyST-Parser](https://github.com/executablebooks/MyST-Parser). For more information about `recommonmark` deprecation and MyST adoption, check [this issue](https://github.com/readthedocs/recommonmark/issues/221).
=> Docs: replace recommonmark by MyST

madminer/analysis/dataanalyzer.py
This PR addresses issue https://github.com/diana-hep/madminer/issues/459 where dictionary values were being injected into a Numpy array as `dict_values` type, instead of their actual type. The fix will be included in the upcoming `0.8.1` release.
=> Fix benchmark array dict_values

environment.yml, madminer/__info__.py, madminer/utils/interfaces/delphes_root.py, madminer/utils/interfaces/lhe.py, madminer/utils/particle.py, setup.py
This PR replaces the unnecessary [scikit-hep](https://github.com/scikit-hep/scikit-hep) dependency (from which MadMiner one uses a tiny part), by the [vector](https://github.com/scikit-hep/vector) package, independently installable from PyPi. In addition to reducing the dependencies _surface_, this change allows the project to make use of the latest versions of `vector`, instead of being stuck at the `<0.6.0` versions of `scikit-hep`.
The refactor has been done making use of `vector.Lorentz` wrapping class: [`VectorObject4D`](https://github.com/scikit-hep/vector/blob/main/src/vector/_backends/object_.py#L921). This class gives us the right abstractions to make direct substitutions for the legacy `skhep.math.vector.LorentzVector` methods.
After the main refactor of the `MadminerParticle` …
=> Replace scikit-hep by vector pkg

.github/workflows/publish.yml
This PR fixes the pinned version of the [publish.yml](https://github.com/diana-hep/madminer/blob/master/.github/workflows/publish.yml) GHA workflow.
GHA PyPi-publish releases: https://github.com/pypa/gh-action-pypi-publish/releases
=> Fix GHA PyPi-publish version

README.md, docs/installation.md, docs/introduction.md, docs/references.md, docs/troubleshooting.md, docs/usage.md
This PR moves all documentation URLs to the bottom of each document by making use of Markdown's indirect references:
```markdown
In the documentation:
[text][identifier]
At the bottom:
[identifier]: url
```
This way of structuring documentation files provides the following benefits:
- Clarity when reading the docs on _raw mode_ (developers).
- Reusability of URLs throughout the same document.
Finally, the [installation section](https://github.com/diana-hep/madminer/blob/ab9c8120622935b1491268e9196c1f5b75e3211d/docs/installation.md) of the docs has been simplified providing the shell scripts needed for installing both [Pythia8](https://pythia.org/) and [Delphes](https://cp3.irmp.ucl.ac.be/projects/delphes) using MadGraph 5 CLI.
=> Strip URLs out of the documentation

madminer/analysis/dataanalyzer.py, madminer/delphes/delphes_reader.py, madminer/lhe/lhe_reader.py, madminer/likelihood/histo.py, madminer/limits/asymptotic_limits.py, madminer/ml/base.py, madminer/utils/ml/trainer.py, madminer/utils/ml/utils.py
This PR updates the current codebase by removing unnecessary constructors and inheritances carried over from the _Python 2 compatibility_ era. In addition, references to the [scikit-hep](https://pypi.org/project/scikit-hep/) package have been removed, as the project [no longer uses it](https://github.com/diana-hep/madminer/pull/458).
The rest of the changes are self explanatory.
=> Python 3 syntax improvements

madminer/ml/double_parameterized_ratio.py, madminer/ml/ensemble.py, madminer/ml/likelihood.py, madminer/ml/parameterized_ratio.py, madminer/ml/score.py
Standard MadMiner _train_ methods return a tuple with the Numpy arrays with training and validation loss, but this was not implemented for the Ensemble methods. With these code changes, the Ensemble _train_one_ method returns a similar tuple, and the _train_all_ method returns a list with N tuples, where N is the number of estimators in the Ensemble.
Also, I updated the documentation to mention explicitly that the train methods return the training and validation losses.
Any feedback is much appreciated.
=> Return arrays with training and validation losses in Ensemble methods + updating documentation

madminer/utils/interfaces/delphes_root.py, madminer/utils/interfaces/lhe.py, madminer/utils/particle.py
This PR addresses issue https://github.com/diana-hep/madminer/issues/470, which describes an exception being raised when the `MadMinerParticle` class is being initialized within several interface modules ([delphes_root.py](https://github.com/diana-hep/madminer/blob/master/madminer/utils/interfaces/delphes_root.py), [lhe.py](https://github.com/diana-hep/madminer/blob/master/madminer/utils/interfaces/lhe.py)...).
The bug was initially introduced on the `scikit-hep` -> `vector` [migration PR](https://github.com/diana-hep/madminer/pull/458), as the _scikit-hep_ based class from which `MadMinerParticle` inherited from (`LorentzVector`) defined default argument values, but the _vector_ based one (`VectorObject4D`) does not.
When using the latter, we must replaced the usual initialization by one …
=> Fix MadMiner particle initialization

madminer/utils/particle.py
This PR addresses issue https://github.com/diana-hep/madminer/issues/470, which describes an exception being raised when the `MadMinerParticle` properties `m` (mass) and `e` (energy) are being accessed.
The bug was initially introduced on the `scikit-hep` -> `vector` [migration PR](https://github.com/diana-hep/madminer/pull/458), as the chosen class to inherit from, [ObjectVector4D](https://github.com/scikit-hep/vector/blob/v0.8.3/src/vector/_backends/object_.py#L921), does not expose does properties. The parent class must be substituted by [MomentumVector4D](https://github.com/scikit-hep/vector/blob/v0.8.3/src/vector/_backends/object_.py#L1353) instead.
=> Replace Madminer particle inherited class

madminer/analysis/dataanalyzer.py, madminer/fisherinformation/geometry.py, madminer/fisherinformation/information.py, madminer/lhe/lhe_reader.py, madminer/limits/asymptotic_limits.py, madminer/ml/base.py, madminer/ml/double_parameterized_ratio.py, madminer/ml/likelihood.py, madminer/ml/morphing_aware.py, madminer/ml/parameterized_ratio.py, madminer/ml/score.py, madminer/plotting/fisherinformation.py, madminer/plotting/limits.py, madminer/sampling/sampleaugmenter.py, madminer/utils/interfaces/delphes_root.py, madminer/utils/ml/models/base.py, madminer/utils/ml/models/batch_norm.py, madminer/utils/ml/models/made.py, madminer/utils/ml/models/made_mog.py, madminer/utils/ml/models/maf.py, madminer/utils/ml/models/maf_mog.py, madminer/utils/ml/models/ratio.py, madminer/utils/ml/models/score.py, madminer/utils/ml/trainer.py, madminer/utils/particle.py, madminer/utils/various.py
This PR continues to migrate Python2 compatible syntax to Python3. The main goal of the PR is to simplify the calls to the _superclass_ of all the defined classes from:
```python3
super(MyClassName, self)
```
to:
```python3
super()
```
This simplification revealed a couple of duplications and typos that required additional consideration:
- The [MorphingAwareRatioEstimator](https://github.com/diana-hep/madminer/blob/v0.8.1/madminer/ml/morphing_aware.py#L13) `super()` call specified the wrong type to infer the superclass from. Check https://github.com/diana-hep/madminer/commit/f1487d6d6cde29f84c7f3ef5cc89723777d8eff2.
- The [QuadraticMorphingAwareRatioEstimator](https://github.com/diana-hep/madminer/blob/v0.8.1/madminer/ml/morphing_aware.py#L96) `super().train` method could fail in its arg. …
=> Migrate super() calls to Python3

environment.yml, madminer/utils/interfaces/lhe.py, setup.py
This PR bumps the [vector](https://github.com/scikit-hep/vector) package dependency to version `0.8.4`, addressing issue https://github.com/diana-hep/madminer/issues/470.
Version `0.8.4` allow the proper subclassing of `Vector` derived classes, as it does not require that children classes belong to its own package. Check [this PR](https://github.com/scikit-hep/vector/pull/128) for details.
In addition, it removes a legacy parenthesis around `particle.phi()`.
=> Fix vector classes inheritance

environment.yml, madminer/delphes/delphes_reader.py, madminer/lhe/lhe_reader.py, madminer/utils/interfaces/delphes_root.py, madminer/utils/interfaces/lhe.py, madminer/utils/particle.py, madminer/utils/various.py, setup.py
This PR covers the introduction of the [scikit-hep/particle](https://github.com/scikit-hep/particle) package into the codebase, to replace most of the hardcoded PDG IDs throughout the codebase.
The particle package allows for the _meaningful_ search of particles by specifying their name, or any other arbitrary filter function thanks to the [Particle.findall(...)](https://github.com/scikit-hep/particle/blob/3dad2d83684aba8e140417274775f1e1621cb3d2/src/particle/particle/particle.py#L1035-L1041) function. In addition, [Particle.from_pdgid(...)](https://github.com/scikit-hep/particle/blob/3dad2d83684aba8e140417274775f1e1621cb3d2/src/particle/particle/particle.py#L1012-L1013) has been used within the MadminerParticle class to obtain the charge of specific particles given their PDG ID (some of …
=> Use particle package as PDG ID utility

environment.yml, madminer/utils/interfaces/lhe.py, setup.py
This PR modernizes syntax around the [scikit-hep/particle](https://github.com/scikit-hep/particle) package upon version `0.16.0` release.
The changes were already hinted by Eduardo Rodriguez on [this PR](https://github.com/diana-hep/madminer/pull/476).
- [Comment](https://github.com/diana-hep/madminer/pull/476#discussion_r696173709) about the neutrino IDs snippet.
- [Comment](https://github.com/diana-hep/madminer/pull/476#discussion_r696177288) about the Standard Model particles.
=> Modernize syntax to particle v0.16.0

.github/workflows/ci.yml, .github/workflows/publish.yml, .readthedocs.yml, docs/installation.md, environment.yml, setup.py
This PR continues the work towards completing issue https://github.com/diana-hep/madminer/issues/482, by dropping support for Python 3.6.
The reason for dropping support, is the lack of [Python Data-classes](https://docs.python.org/3.7/library/dataclasses.html) (introduced in Python 3.7), in addition to the upcoming release of Python 3.10 (there would be too many versions being supported otherwise: 3.6, 3.7, 3.8, 3.9 and 3.10).
Finally, Python 3.9 has been added to [the CI workflow matrix](https://github.com/Sinclert/madminer/blob/102936951c0d78c42ac710f7929c681032010564/.github/workflows/ci.yml#L29).
=> Drop Python 3.6 support

environment.yml, madminer/analysis/dataanalyzer.py, madminer/delphes/delphes_reader.py, madminer/lhe/lhe_reader.py, madminer/plotting/distributions.py, madminer/sampling/combine.py, madminer/sampling/sampleaugmenter.py, madminer/utils/interfaces/delphes_root.py, madminer/utils/interfaces/hdf5.py, madminer/utils/morphing.py, setup.py
This PR upgrades the minimum [numpy](https://github.com/numpy/numpy) requirements to version `1.20.0`. In addition, it substitute the [deprecated `dtypes`](https://numpy.org/doc/stable/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated) by their closest equivalents:
- `np.int` -> `int`. Equivalent.
- `np.bool` -> `bool`. Equivalent.
- `np.float` -> `np.float64`. More precise.
=> Bump Numpy version to 1.20.0+

madminer/utils/interfaces/lhe.py
This PR addresses issue https://github.com/madminer-tool/madminer/issues/494 by providing a _partial_ solution to the identification of [all PDF sets](https://lhapdf.hepforge.org/pdfsets.html) in the _nuisance parameters_ LHE file reading function.
--
cc @konda111
=> Add MWST sets to the accepted nuisance params.

examples/tutorial_toy_simulator/tutorial_toy_simulator.ipynb
The [first non-beta release of `black`, `22.1.0`](https://black.readthedocs.io/en/stable/change_log.html) introduced some small formatting changes, most notably the removal of spaces around powers `**`. This updates the code to the latest version of `black`.
#480 introduced the `black` formatting for the example notebooks, and the CI currently fails due to the changes to `black`, as it checks for formatting changes:
https://github.com/madminer-tool/madminer/blob/6556f164725baab6b79e5ffa2a64913a0ac50f7a/.github/workflows/ci.yml#L39 
This PR will fix that part of the CI.
This PR does not touch the main library itself, and running `black` over that would currently touch 47 files. That is a bigger change that may be worth considering separately.
=> style: apply black 22.1 formatting to notebooks

madminer/delphes/delphes_reader.py, madminer/fisherinformation/geometry.py, madminer/lhe/lhe_reader.py, madminer/likelihood/histo.py, madminer/models/benchmarks.py, madminer/utils/histo.py, madminer/utils/interfaces/hdf5.py, madminer/utils/interfaces/lhe.py
This PR contains a series of readability and syntax improvements since the last release.
Listed:
- Replace short for-loops by list comprehensions and extend calls.
- Simplify how the [Benchmark](https://github.com/madminer-tool/madminer/blob/0df492859a3c4b0208cb6a0127761fec22e51588/madminer/models/benchmarks.py#L9-L78) model have its `values` dictionary built.
- Simplify how the [FiniteDiffBenchmark](https://github.com/madminer-tool/madminer/blob/0df492859a3c4b0208cb6a0127761fec22e51588/madminer/models/benchmarks.py#L82-L106) model have its `shift_names` dictionary built.
- Improve readability on `histo.py` [_calculate_binning](https://github.com/madminer-tool/madminer/blob/0df492859a3c4b0208cb6a0127761fec22e51588/madminer/utils/histo.py#L84-L101) function.
- Removes the default values of …
=> Improve and simplify Python syntax

setup.cfg
Remove upper bound on python_requires to avoid artificially making madminer impossible to install with future releases of Python.
- c.f. https://iscinumpy.dev/post/bound-version-constraints/
=> build: Remove upper bound on python_requires

.github/workflows/ci.yml, .github/workflows/docs.yml
Add `workflow_dispatch` triggers to be able to run workflows on demand, and add concurrency to automatically cancel workflows that have been superseded.
=> ci: Add workflow_dispatch and concurrency to CI

docs/conf.py
The current `language = None` setting results in a Sphinx warning, which in CI is treated as an error, so CI fails:
```
Running Sphinx v5.1.1
Warning, treated as error:
Invalid configuration value found: 'language = None'. Update your configuration to a valid language code. Falling back to 'en' (English).
make: *** [Makefile:1[9](https://github.com/madminer-tool/madminer/runs/8015958086?check_suite_focus=true#step:5:10): html] Error 2
Error: Process completed with exit code 2.
```
taken from https://github.com/madminer-tool/madminer/runs/8015958086.
=> docs: set language to fix warning

examples/morphing_basis/morphing_example.ipynb, examples/tutorial_particle_physics/2b_delphes_level_analysis.ipynb
This PR fixes typos throughout the [morphing_example.ipynb](https://github.com/madminer-tool/madminer/blob/master/examples/morphing_basis/morphing_example.ipynb) notebook.
This notebooks was merged as part of the _adding overdetermined morphing_ effort in [this PR](https://github.com/madminer-tool/madminer/pull/506).
=> Fix morphing_example notebook typos

madminer/analysis/dataanalyzer.py, madminer/likelihood/base.py, madminer/likelihood/histo.py, madminer/likelihood/neural.py, madminer/limits/asymptotic_limits.py, madminer/sampling/sampleaugmenter.py
This PR refactors DataAnalyzer class methods to reuse same `start_event` and `end_event` calculation private methods.
This was possible by:
- Defining a [_calculate_start_event](https://github.com/madminer-tool/madminer/blob/03d8e6ae5fd07a983957c51d9ee601c252909c24/madminer/analysis/dataanalyzer.py#L921-L936) private method (duh).
- Defining a [_calculate_end_event](https://github.com/madminer-tool/madminer/blob/03d8e6ae5fd07a983957c51d9ee601c252909c24/madminer/analysis/dataanalyzer.py#L938-L953) private method (duh).
- Defining a [_is_valid_split](https://github.com/madminer-tool/madminer/blob/03d8e6ae5fd07a983957c51d9ee601c252909c24/madminer/analysis/dataanalyzer.py#L598-L602) private method.
- Doing all the _split validation_ checks once, at the beginning of the public methods.
=> Refactor DataAnalyzer train / test / validation split calc.

madminer/utils/interfaces/hdf5.py
This PR **partially** addresses issue https://github.com/madminer-tool/madminer/issues/517 by reducing the logger level of HDF5 loaders from `ERROR` to `INFO`.
It was reported that `ERROR` messages make user feels like there was something wrong with their setup file, which it may very well not be the case.
=> Change HDF5 load logger messages to INFO

madminer/fisherinformation/information.py, madminer/sampling/sampleaugmenter.py
This PR **partially** addresses issue https://github.com/madminer-tool/madminer/issues/517 by restricting the calculation of fisher information when `nuisance_morpher` is `None`.
I find this approach better than restoring DataAnalyzer safe-guard overriding user input for `include_nuisance_parameters` ([reference](https://github.com/madminer-tool/madminer/blob/v0.8.3/madminer/analysis/dataanalyzer.py#L71-L77)) for a couple of reasons:
- It is better for traceability purposes.
- It harmonised all nuisance params existance checks, as the `self.nuisance_morpher is not None` snippet is found in many other places within the codebase.
- Removed unused local variable within the fisher calculation method (https://github.com/madminer-tool/madminer/commit/1d8210a4cacea9795828840e57e69174dc3d77e5).
- …
=> Restrict Fisher information calc. based on nuisance_morpher

environment.yml
This PR fixes a missing dependency within the conda `environmnt.yml` file, after merging PR https://github.com/madminer-tool/madminer/pull/506.
=> Add sympy to conda dependency list

.github/workflows/ci.yml, pyproject.toml, setup.cfg
This PR drops support for Python 3.7 starting next version (possible `0.10.0`), given how close we are from official support drop (according to [this document](https://devguide.python.org/versions/), June 2023).
=> Drop Python 3.7 support

MANIFEST.in
This PR removes the unnecessary `MANIFEST.in` file from the project.
Upon preliminar testing, setuptools has been automatically picking up `setup.cfg` metadata required files, when building _source distributions_, for a few versions now (therefore, issue https://github.com/pypa/setuptools/issues/2821 should have been closed some time ago).
Given that we are only leveraging `MANIFEST.in` to include metadata required file, we can get rid of it.
=> Remove unnecessary MANIFEST.in

environment.yml, madminer/utils/interfaces/delphes_root.py, setup.cfg
This PR bumps the uproot dependency from versions `>=3.14.1` to versions `>=4.0.0`, overseeding https://github.com/madminer-tool/madminer/pull/511.
It also states Numpy as the _default-library_. According to the [uproot 3 -> 4 migration docs](https://uproot.readthedocs.io/en/latest/uproot3-to-4.html):
> **Uproot 3 chooses between NumPy and Awkward Array** based on the type of the data. Since NumPy arrays and Awkward Arrays have different methods and properties, it’s safer to write scripts with a deterministic output type.
>
> Note: Awkward Array is not one of Uproot 4’s formal requirements. If you don’t have awkward installed, array() and arrays() **will raise errors explaining how to install Awkward Array or switch to library="np"**
=> feat: switch from uproot3 to uproot

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/publish.yml, Makefile
* Use 'uv pip' for all calls to 'pip install' in CI workflows.
- c.f. https://github.com/astral-sh/uv/
* Use 'pipx run' over a Make command.
```
* Use 'uv pip' for all calls to 'pip install' in CI workflows.
- c.f. https://github.com/astral-sh/uv/
* Use 'pipx run' over a Make command.
```
=> ci: Use uv for all pip installs

.github/workflows/ci.yml, .github/workflows/docs.yml, .github/workflows/publish.yml
* Update actions/checkout to v4.
* Update actions/setup-python to v5.
* Use python '3.x' for non tests.
=> ci: Update GitHub Actions

.github/workflows/ci.yml
* Add Python 3.11 and 3.12 to tests.
* Only install required tools for linting.
=> ci: Add all supported Pythons to testing
